services:
  app:
    build:
      context: .
      dockerfile: services/inference_srv/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG_DIR: /debug
    volumes:
      - ./debug:/debug
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  ygo_srv:
    build:
      context: .
      dockerfile: services/tcg_srvs/ygo_srv/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./services/tcg_srvs/ygo_srv/data:/data
    restart: unless-stopped