services:
  app:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG_DIR: /debug
    volumes:
      - ./debug:/debug
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped